import type { Metadata } from "next";
import classNames from "classnames";
import "./../styles/globals.scss";
import { poppins } from "@/shared/fonts";
import "bootstrap/dist/css/bootstrap.min.css";
import LayoutCommonComponents from "@/components/layoutCommonComponents/LayoutCommonComponents";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={classNames(poppins.variable)}>
          <LayoutCommonComponents >
            {children}
          </LayoutCommonComponents>
      </body>
    </html>
  );
}
